name: JMeter Load Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-jmeter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create reports directory
        run: mkdir -p reports/html

      - name: Run JMeter Test
        uses: QAInsights/PerfAction@v5.6.2
        with:
          test-plan-path: ./TC03_LOB_.jmx

      - name: Debug - Show JMeter log
        run: cat jmeter.log || true

      - name: Debug - Show reports directory recursively
        run: ls -lR reports || true

      - name: Debug - Find all .jtl files under reports
        run: find reports -name '*.jtl' || true

      - name: Debug - Show size of result.jtl if exists
        run: ls -lh reports/result.jtl || echo "File reports/result.jtl not found"

      - name: Upload Results (all .jtl files under reports)
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: reports/*.jtl
          if-no-files-found: error
          compression-level: 6

      - name: Upload HTML Reports
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-html-reports
          path: reports/html
          if-no-files-found: error
