name: JMeter Load Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-jmeter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create reports directory
        run: mkdir -p reports/html

      - name: Run JMeter Test
        uses: QAInsights/PerfAction@v5.6.2
        with:
          test-plan-path: ./TC03_LOB_.jmx
          args: "-l ./reports/result.jtl -e -o ./reports/html/"

      - name: Debug - List generated files
        run: |
          echo "=== Reports Directory Contents ==="
          ls -R reports || true

      - name: Upload Raw JMeter Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: reports/result.jtl
          if-no-files-found: error

      - name: Upload HTML Reports
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-html-reports
          path: reports/html
          if-no-files-found: error
